# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: function_types.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class FunctionTypesEnum(betterproto.Enum):
    Finish = 0
    Data = 1
    Start = 2
    Load = 3
    GetResult = 4
    Stop = 5


@dataclass
class FunctionTypes(betterproto.Message):
    function_types: "FunctionTypesEnum" = betterproto.enum_field(1)
