# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: function_types.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class FunctionTypesEnum(betterproto.Enum):
    Unknown = 0
    Finish = 1
    Data = 2
    Start = 3
    Load = 4
    GetResult = 5
    Stop = 6


@dataclass
class FunctionTypes(betterproto.Message):
    function_types: "FunctionTypesEnum" = betterproto.enum_field(1)
