# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: opencv.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class OcvMat(betterproto.Message):
    rows: int = betterproto.int32_field(1)
    cols: int = betterproto.int32_field(2)
    mat_data_type: int = betterproto.int32_field(3)
    mat_data_size: int = betterproto.int32_field(4)
    mat_data: bytes = betterproto.bytes_field(5)
