# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: person_info.proto, person.proto, persons.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class Sex(betterproto.Enum):
    M = 0
    F = 1
    O = 2


@dataclass
class PersonInfo(betterproto.Message):
    age: int = betterproto.int32_field(1)
    sex: "Sex" = betterproto.enum_field(2)
    height: int = betterproto.int32_field(3)


@dataclass
class Person(betterproto.Message):
    info: "PersonInfo" = betterproto.message_field(1)
    friends: List["Friend"] = betterproto.message_field(2)


@dataclass
class Friend(betterproto.Message):
    friendship_duration: float = betterproto.float_field(1)
    shared_hobbies: List[str] = betterproto.string_field(2)
    person: "Person" = betterproto.message_field(3)


@dataclass
class Persons(betterproto.Message):
    person: List["Person"] = betterproto.message_field(1)
